config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    get 'sign_in', to: 'users/sessions#new', as: :new_user_session
  end

  scope defaults: { format: :json } do
    namespace :api do
      namespace :v1 do
        get 'vaults/:id' => 'vaults#show', constraints: { id: Vault::NAME_FORMAT }
      end
    end
  end

  scope constraints: { id: Vault::NAME_FORMAT } do
    resources :vaults
  end

  authenticated :user do
    root to: 'vaults#index', as: :signed_root
  end

  root 'users/sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :lockable, :trackable, :omniauthable, omniauth_providers: [:google_oauth2]
  validates :refresh_token, presence: true
  before_create { Users::GenerateDeployToken.call(self) }
end

app/models/vault.rb
class Vault < ApplicationRecord
  NAME_FORMAT = /[a-zA-Z0-9\-\.]+/
  validates :name, presence: true, uniqueness: true, format: { with: NAME_FORMAT }
  validates :files, presence: true

  attribute :files
  attr_encrypted :files, key: proc { Settings.database_encryption_key }

  has_many :archives, dependent: :delete_all, class_name: 'VaultArchive'

  before_update :prepare_archive

  def to_param
    name
  end

  private

  def prepare_archive
    archives.new(files: files_was) if files_changed?
  end
end

app/models/vault_archive.rb
class VaultArchive < ApplicationRecord
  validates :files, presence: true
  belongs_to :vault, inverse_of: :archives

  attribute :files
  attr_encrypted :files, key: proc { Settings.database_encryption_key }
end

app/controllers/api/v1/api_controller.rb
module Api
  module V1
    class ApiController < ActionController::API
      rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

      private

      def id_param
        params.require(:id)
      end

      def record_not_found(error)
        render json: { error: error.message }, status: :not_found
      end
    end
  end
end

app/controllers/api/v1/vaults_controller.rb
module Api
  module V1
    class VaultsController < ApiController
      before_action :verify_user

      def show
        @vault = VaultRepo.fetch(id_param)
        send_data Vaults::FetchFiles.call(@vault, timestamp_param),
                  type: 'application/octet-stream',
                  disposition: 'attachment',
                  filename: "#{@vault.name}.tar.enc"
      end

      private

      def verify_user
        render status: :unauthorized, json: { error: 'Verification failure' } unless Users::Verify.call(deploy_user)
      end

      def deploy_user
        @deploy_user ||= User.find_by!(deploy_token: deploy_token_param)
      end

      def timestamp_param
        params[:timestamp]
      end

      def deploy_token_param
        params.require(:deploy_token)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users/omniauth_callbacks_controller.rb
module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def google_oauth2
      @user = Oauth::AuthorizeByGoogle.call(omniauth_data)
      respond_with(@user, :google_oauth2)
    end

    def failure
      redirect_to new_user_session_path
    end

    private

    def respond_with(user, kind)
      if user.persisted?
        sign_in_and_redirect user, event: :authentication
        set_flash_message(:notice, :success, kind: kind) if is_navigational_format?
      else
        set_flash_message(:notice, :error, kind: kind) if is_navigational_format?
        redirect_to root_path
      end
    end

    def omniauth_data
      request.env['omniauth.auth']
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < ApplicationController
    def new
    end
  end
end

app/controllers/vaults_controller.rb
class VaultsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @vaults = VaultRepo.all
  end

  def new
    @vault = VaultRepo.build
  end

  def create
    @vault = VaultRepo.create(create_vault_params)
    if @vault.persisted?
      render status: :created, json: { redirect_to: vault_path(@vault) }
    else
      render status: :unprocessable_entity, json: { errors: @vault.errors }
    end
  end

  def update
    @vault = VaultRepo.fetch(id_param)
    if @vault.update_attributes(update_vault_params)
      render status: :created, json: {}
    else
      render status: :unprocessable_entity, json: { errors: @vault.errors }
    end
  end

  def show
    @vault = VaultRepo.fetch(id_param)
    respond_to do |format|
      format.html
      format.json { render json: { name: @vault.name, files: @vault.files } }
    end
  end

  private

  def id_param
    params.require(:id)
  end

  def create_vault_params
    params.require(:vault).permit(:name, :files)
  end

  def update_vault_params
    params.require(:vault).permit(:files)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def react_component(klass, props = {}, js = nil)
    content_for(:javascript) { javascript_pack_tag(js) } if js
    content_tag 'div', '', data: { 'react-class' => klass, 'react-props' => props }
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/vaults_helper.rb
module VaultsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= Settings.page.title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_pack_tag 'commons' %>
    <%= content_for(:javascript) %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash' %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_flash.html.haml
- unless flash.empty?
  .container
    .row
      .col-md-12
        - flash.each do |type, message|
          .alert.alert-info= message

app/views/shared/_header.html.haml
%nav.navbar.navbar-inverse.navbar-fixed-top
  .container-fluid
    - if content_for?(:toolbar)
      = content_for(:toolbar)
    - else
      .nav.navbar-left
        %a.navbar-brand{ href: '/' }
          %span.glyphicon.glyphicon-lock
          = Settings.page.title
    - if user_signed_in?
      %ul.nav.navbar-nav.navbar-right
        %li= link_to t('.vaults'), vaults_path
        %li= link_to 'Log out', destroy_user_session_path, method: :delete

app/views/vaults/index.html.haml
.row
  .col-md-8.col-sm-offset-2
    .page-header
      .pull-right= link_to t('.new'), new_vault_path, class: 'btn btn-md btn-success'
      %h2 Vaults
.row
  .col-md-8.col-sm-offset-2
    %table.table.table-striped.table-bordered.table-hover
      %thead
        %tr
          %th= t('.name')
          %th.col-md-3= t('.updated_at')
      %tbody
        - @vaults.each do |vault|
          %tr
            %td= link_to vault.name, vault
            %td= l(vault.updated_at, format: :long)
        - if @vaults.empty?
          %tr
            %td{ colspan: 2 }= t('.empty')

app/views/vaults/new.html.haml
.row
  .col-md-6.col-sm-offset-3
    .page-header
      %h2 Create new vault
    = react_component 'CreateVaultForm', {}, 'create_vault.js'

app/views/vaults/show.html.haml
- content_for :toolbar do
  = react_component 'VaultToolbar'
= react_component 'ManageVault', { name: @vault.name }, 'manage_vault'